// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Neon: миграциям нужно прямое (unpooled) соединение — advisory locks
    // Prisma Migrate не переживают PgBouncer в transaction-режиме, которым
    // работает пуленный DATABASE_URL. Рантайм-клиент (src/lib/prisma.ts)
    // по-прежнему берёт пуленный DATABASE_URL напрямую — это разные пути.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
