import { prisma } from "@/lib/prisma";
import { PAYOUT_MINIMUM_KOPECKS } from "@/lib/partners";
import { markCommissionPaid } from "./actions";

const rub = (kopecks: number) => `${(kopecks / 100).toLocaleString("ru-RU")} ₽`;

export default async function AdminPartnersPage() {
 const [partners, commissions, requests] = await Promise.all([prisma.partner.findMany({ include: { user: true, clicks: true, commissions: true }, orderBy: { createdAt: "desc" } }), prisma.referralCommission.findMany({ include: { partner: { include: { user: true } }, customer: true }, orderBy: { createdAt: "desc" } }), prisma.partnerRequest.findMany({ orderBy: { createdAt: "desc" } })]);
 const approved = commissions.filter((c) => c.status === "APPROVED");
 const total = commissions.reduce((sum, c) => sum + c.amount, 0);
 return <main className="p-6"><h1 className="font-display text-2xl text-parchment-hi">Партнёрская программа</h1><div className="mt-6 grid gap-4 md:grid-cols-4">{[["Партнёры",String(partners.length)],["Переходы",String(partners.reduce((s,p)=>s+p.clicks.length,0))],["Начислено",rub(total)],["К выплате",rub(approved.reduce((s,c)=>s+c.amount,0))]].map(([label,value])=><div key={label} className="rounded border border-void-border bg-void-elevated p-4"><p className="font-technical text-[10px] uppercase text-bone-dim">{label}</p><p className="mt-2 font-display text-2xl text-gold-bright">{value}</p></div>)}</div><section className="mt-8"><h2 className="font-display text-xl text-parchment-hi">Партнёры</h2><div className="mt-3 space-y-3">{partners.map((p)=>{const due=p.commissions.filter(c=>c.status==="APPROVED").reduce((s,c)=>s+c.amount,0);return <div key={p.id} className="rounded border border-void-border bg-void-elevated p-4 font-body text-sm text-bone"><b>{p.user.name}</b> · {p.user.email}<br/><span className="text-bone-dim">Ссылка: /r/{p.code} · промокод: {p.promoCode} · переходов: {p.clicks.length} · к выплате: {rub(due)}{due >= PAYOUT_MINIMUM_KOPECKS ? " — порог достигнут" : ""}</span>{p.payoutDetails && <p className="mt-2 text-bone-dim">Реквизиты: {p.payoutDetails}</p>}</div>})}</div></section><section className="mt-8"><h2 className="font-display text-xl text-parchment-hi">Начисления и выплаты</h2><div className="mt-3 space-y-2">{commissions.map((c)=><div key={c.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-void-border bg-void-elevated p-4 font-body text-sm text-bone"><span>{c.partner.user.name} ← {c.customer.email} · {c.kind} · {rub(c.amount)} · {c.status}</span>{c.status === "APPROVED" && <form action={markCommissionPaid}><input type="hidden" name="id" value={c.id}/><button className="rounded border border-gold px-3 py-2 font-technical text-xs uppercase text-gold-bright">Отметить выплату</button></form>}</div>)}</div></section><section className="mt-8"><h2 className="font-display text-xl text-parchment-hi">Запросы на партнёрства</h2><div className="mt-3 space-y-2">{requests.map((r)=><div key={r.id} className="rounded border border-void-border bg-void-elevated p-4 font-body text-sm text-bone"><b>{r.type}</b> · {r.name} · {r.email}{r.company && ` · ${r.company}`}<p className="mt-1 text-bone-dim">{r.message}</p></div>)}</div></section></main>;
}
